CREATE TABLE IF NOT EXISTS lector (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    rut VARCHAR(12) NOT NULL UNIQUE,
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS libro (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ejemplar (
    id SERIAL PRIMARY KEY,
    estado VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    libro_id INTEGER NOT NULL REFERENCES libro(id)
);

CREATE TABLE IF NOT EXISTS prestamo (
    id SERIAL PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    fecha_devolucion DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    lector_id INTEGER NOT NULL REFERENCES lector(id),
    ejemplar_id INTEGER NOT NULL REFERENCES ejemplar(id)
);

CREATE TABLE IF NOT EXISTS multa (
    id SERIAL PRIMARY KEY,
    dias_atraso INTEGER NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    pagada BOOLEAN NOT NULL DEFAULT FALSE,
    prestamo_id INTEGER NOT NULL REFERENCES prestamo(id)
);
