

services:
  postgres:
    image: postgres:16
    container_name: sigu_ucn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sigu_ucn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/migrations/V001__modulo_tutorias.sql:/docker-entrypoint-initdb.d/V001__modulo_tutorias.sql
      - ./db/migrations/V002__crear_rol_tutor.sql:/docker-entrypoint-initdb.d/V002__crear_rol_tutor.sql

volumes:
  postgres_data: